---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: yes
  tasks:
  - name: check partition sdb1 exist
    assert:
      that: hostvars[inventory_hostname].ansible_devices.sdb.partitions.sdb1 is defined

  - name: run pvscan
    command: pvscan
    register: output

  - name: check /dev/sdb1 pv exists
    assert:
      that: "'/dev/sdb1' in output.stdout"

  - name: run vgscan
    command: vgscan
    register: output

  - name: check ansible_vg vg exists
    assert:
      that: "'ansible_vg' in output.stdout"

  - name: run lvscan
    command: lvscan
    register: output

  - name: check ansible_lv lv exists
    assert:
      that: "'ansible_lv' in output.stdout"
